// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var buildSelects, getConfiguration, render, settings;
    settings = {
      forms: {
        round: "link image",
        square: "link image"
      },
      holes: ["Top left corner", "Top right corner", "Bottom left corner", "Bottom right corner"],
      fonts: ["Times New Roman", "Arial"],
      materials: ["Steel", "Mystic material"]
    };
    buildSelects = function() {
      var form, forms, hole, holes, materials, option, selects, _i, _j, _len, _len1, _ref, _ref1;
      selects = $('.selects');
      forms = $('<select></select>');
      forms.attr('id', 'forms');
      option = $('<option selected disabled>Forms</option>');
      option.appendTo(forms);
      for (form in settings.forms) {
        option = $("<option>" + form + "</option>");
        option.appendTo(forms);
      }
      forms.appendTo(selects);
      holes = $('<select multiple></select>');
      holes.attr('id', 'holes');
      option = $('<option disabled>Holes</option>');
      option.appendTo(holes);
      _ref = settings.holes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        hole = _ref[_i];
        option = $("<option>" + hole + "</option>");
        option.appendTo(holes);
      }
      holes.appendTo(selects);
      materials = $('<select></select>');
      materials.attr('id', 'materials');
      option = $('<option selected disabled>Materials</option>');
      _ref1 = settings.materials;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        hole = _ref1[_j];
        option = $("<option>" + hole + "</option>");
        option.appendTo(materials);
      }
      return materials.appendTo(selects);
    };
    getConfiguration = function() {};
    render = function() {
      var conf, field;
      conf = getConfiguration();
      return field = $('preview');
    };
    buildSelects();
    $('select').selectpicker();
    return $('select').each(function() {
      return $(this).change(function() {
        return render();
      });
    });
  });

}).call(this);

//# sourceMappingURL=signs.js.map
