// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var getConfiguration, render, settings;
    settings = {
      fonts: ["Times New Roman", "Arial"],
      materials: ["Steel", "Mystic material"]
    };
    getConfiguration = function() {};
    render = function() {
      var field;
      return field = $('preview');
    };
    $('.selectpicker').selectpicker();
    return $('select').each(function() {
      return $(this).change(function() {
        return render();
      });
    });
  });

}).call(this);

//# sourceMappingURL=signs.js.map
