// Generated by CoffeeScript 1.8.0
(function() {
  $(function() {
    var settings;
    settings = {
      fonts: ["Times New Roman", "Arial"],
      materials: ["Steel", "Mystic material"]
    };
    $('.selectpicker').selectpicker();
    return $('select').each(function() {
      return $(this).change(function() {
        return console.log(this);
      });
    });
  });

}).call(this);

//# sourceMappingURL=signs.js.map
